#! /bin/bash

usage()
{
    echo "Usage: `basename $0` [-qv] [-l LOGFILE] -d DEVICE input_file [input_file2...]"
    exit 1
}

while getopts m:d:p OPTION
do
    case $OPTION in
        m)
            MODE_TYPE=$OPTARG
            ;;
        d)
            DATA_PATH=$OPTARG
            ;;
        p)
            PORT_OPEN=y
            ;;
        \?)
            usage
            ;;
    esac
done


docker_mode()
{
    DOCKER_CMD="docker run -d"
    if [ "$PORT_OPEN" == y ]; then
        DOCKER_CMD="${DOCKER_CMD} -p 27017:27017"
    fi

    if [ ! -z "$DATA_PATH" ]; then
        DOCKER_CMD="${DOCKER_CMD} -v ${DATA_PATH}:/data/db"
    fi

    DOCKER_CMD="${DOCKER_CMD} --name mongo mongo:3.2.4"

    if [ -z $(docker images -q mongo:3.2.4) ];then
        docker pull mongo:3.2.4
    fi

    if [ -z $(docker ps -a -q -f "name=mongo") ]; then
        eval $DOCKER_CMD
    fi

    if [ -z $(docker ps -q -f "name=mongo") ]; then
        docker start mongo
    fi

    if [ -z $(docker images -q  multi-process-crawler:latest) ]; then
        wget https://raw.githubusercontent.com/yejianfei/multi-process-crawler/master/docker/Dockerfile
        docker build -t multi-process-crawler:latest .
        rm -rf Dockerfile
    fi

    if [ -z $(docker ps -a -q -f "name=multi-process-crawler") ]; then
        docker run -d -p 9000:9000 -p 9001:9001 --name multi-process-crawler --link mongo:mongo multi-process-crawler:latest
    elif [ -z $(docker ps -q -f "name=multi-process-crawler") ]; then
        docker start multi-process-crawler
    fi

}

other()
{
    # check pip command and install
    if ! command -v pip > /dev/null 2&>1; then
        wget https://bootstrap.pypa.io/get-pip.py
        sudo python get-pip.py
        rm -rf get-pip.py
        rm -rf 1
    fi

    # check virtualenv command and install
    if ! command -v virtualenv > /dev/null 2&>1; then
        pip install virtualenv
    fi

    if [ -d multi-process-crawler ]; then
        rm -rf multi-process-crawler
    fi
    # clone source from git
    git clone https://github.com/yejianfei/multi-process-crawler.git

    # install deps
    virtualenv multi-process-crawler/env
    source multi-process-crawler/env/bin/activate
    pip install -r multi-process-crawler/requirements.txt

    # exit virtualenv env
    deactivate
}


if [ "$MODE_TYPE" == "docker" ]; then
    docker_mode
else
    # ubuntu server
    if [ -f /etc/debian_version ]; then

        # check sudo command and install
        if ! command -v sudo > /dev/null 2&1>1; then
            apt-get install sudo -y
        fi

        # install deps command
        sudo apt-get update
        sudo apt-get install -y python wget git
    fi

    # mac osx
    if [ "$(uname)" == "Darwin" ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install wget
    fi
    other
fi