#! /bin/bash


# ubuntu server
if [ -f /etc/debian_version ]; then

    # check sudo command and install
    if ! command -v sudo > /dev/null 2&1>1; then
        apt-get install sudo -y
    fi

    # install deps command
    sudo apt-get update
    sudo apt-get install -y python wget git
fi

# mac osx
if [ "$(uname)" == "Darwin" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install wget
fi


docker()
{
    echo "docker"
}

if [ "$1" == "--docker" ]; then
    docker()
else

    # check pip command and install
    if ! command -v pip > /dev/null 2&>1; then
        wget https://bootstrap.pypa.io/get-pip.py
        sudo python get-pip.py
        rm -rf get-pip.py
        rm -rf 1
    fi

    # check virtualenv command and install
    if ! command -v virtualenv > /dev/null 2&>1; then
        pip install virtualenv
    fi

    if [ -d multi-process-crawler ]; then
        rm -rf multi-process-crawler
    fi
    # clone source from git
    git clone https://github.com/yejianfei/multi-process-crawler.git

    # install deps
    virtualenv multi-process-crawler/env
    source multi-process-crawler/env/bin/activate
    pip install -r multi-process-crawler/requirements.txt

    # exit virtualenv env
    deactivate
fi


